# Generated by Django 2.2.12 on 2021-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('data', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
